//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean grab
        {
            get
            {
                return SteamVR_Actions.default_grab;
            }
        }
        
        public virtual SteamVR_Action_Vector2 touchpad
        {
            get
            {
                return SteamVR_Actions.default_touchpad;
            }
        }
        
        public virtual SteamVR_Action_Boolean click
        {
            get
            {
                return SteamVR_Actions.default_click;
            }
        }
        
        public virtual SteamVR_Action_Boolean trigger
        {
            get
            {
                return SteamVR_Actions.default_trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean left_action1
        {
            get
            {
                return SteamVR_Actions.default_left_action1;
            }
        }
        
        public virtual SteamVR_Action_Boolean left_action2
        {
            get
            {
                return SteamVR_Actions.default_left_action2;
            }
        }
        
        public virtual SteamVR_Action_Boolean right_action1
        {
            get
            {
                return SteamVR_Actions.default_right_action1;
            }
        }
        
        public virtual SteamVR_Action_Boolean right_action2
        {
            get
            {
                return SteamVR_Actions.default_right_action2;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
